server:
  port: 9586

spring:
  application:
    name: cloud-gateway-order
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/getPayMent/**

eureka:
  client:
    #向服务中心注册自己
    register-with-eureka: true
    fetch-registry: true
    #是否从EurekaServer抓取已有的注册信息，默认为True，单节点无所谓，但是集群需要配置，才能配合ribbon使用负载均衡
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个网址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
